extends Node

enum Officer {
	NONE,
	PRESSLEY,
	TORGON,
	FAROQ_KHAN, # Boost food production
	SAM_CARTER,
	GOVERNOR_JERREROD, # Boost habitation capacity
	MARY_WATNEY,
	DR_DORIAN
}

enum CrewmateStatus {
	HEALTHY,
	INFECTED,
	INJURED,
	CRITICAL,
}

enum UpgradeId {
	NONE,
	CREW_SUPPLIES_FOOD_2,
	CREW_SUPPLIES_FOOD_3,
	CREW_SUPPLIES_WATER_2,
	CREW_SUPPLIES_WATER_3,
	CREW_SUPPLIES_AIR_2,
	CREW_SUPPLIES_AIR_3,
	HABITATION_MEDICAL_HOUSE_2,
	HABITATION_MEDICAL_HOUSE_3,
	HABITATION_MEDICAL_CLINIC_1,
	HABITATION_MEDICAL_CLINIC_2,
	HABITATION_MEDICAL_CLINIC_3,
	AGRI_SPACEDUST,
	AGRI_PHOTOSYNTHESIS,
	AGRI_EXTRACT_FUILD,
	AGRI_SPACEDUST_ENHANCED,
	AGRI_HARMONIC_CYCLE,
	AGRI_ACCEL_GROWTH,
	AGRI_OPTIMIZED_DESIGN
}